/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnalyzeReturnRouteImport } from './routes/analyze-return'
import { Route as AssignedRouteImport } from './routes/assigned'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as ControlledLearningRouteImport } from './routes/controlled-learning'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as FraudRadarRouteImport } from './routes/fraud-radar'
import { Route as ModelRegistryRouteImport } from './routes/model-registry'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'
import { Route as GovernanceRetrainingRouteImport } from './routes/governance.retraining'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeReturnRoute = AnalyzeReturnRouteImport.update({
  id: '/analyze-return',
  path: '/analyze-return',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignedRoute = AssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlledLearningRoute = ControlledLearningRouteImport.update({
  id: '/controlled-learning',
  path: '/controlled-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRadarRoute = FraudRadarRouteImport.update({
  id: '/fraud-radar',
  path: '/fraud-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRegistryRoute = ModelRegistryRouteImport.update({
  id: '/model-registry',
  path: '/model-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRetrainingRoute = GovernanceRetrainingRouteImport.update({
  id: '/governance/retraining',
  path: '/governance/retraining',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/analyze-return': typeof AnalyzeReturnRoute
  '/assigned': typeof AssignedRoute
  '/audit-log': typeof AuditLogRoute
  '/controlled-learning': typeof ControlledLearningRoute
  '/dashboard': typeof DashboardRoute
  '/data-quality': typeof DataQualityRoute
  '/fraud-radar': typeof FraudRadarRoute
  '/model-registry': typeof ModelRegistryRoute
  '/returns': typeof ReturnsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/settings': typeof SettingsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/governance/retraining': typeof GovernanceRetrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/analyze-return': typeof AnalyzeReturnRoute
  '/assigned': typeof AssignedRoute
  '/audit-log': typeof AuditLogRoute
  '/controlled-learning': typeof ControlledLearningRoute
  '/dashboard': typeof DashboardRoute
  '/data-quality': typeof DataQualityRoute
  '/fraud-radar': typeof FraudRadarRoute
  '/model-registry': typeof ModelRegistryRoute
  '/returns': typeof ReturnsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/settings': typeof SettingsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/governance/retraining': typeof GovernanceRetrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/analyze-return': typeof AnalyzeReturnRoute
  '/assigned': typeof AssignedRoute
  '/audit-log': typeof AuditLogRoute
  '/controlled-learning': typeof ControlledLearningRoute
  '/dashboard': typeof DashboardRoute
  '/data-quality': typeof DataQualityRoute
  '/fraud-radar': typeof FraudRadarRoute
  '/model-registry': typeof ModelRegistryRoute
  '/returns': typeof ReturnsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/settings': typeof SettingsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/governance/retraining': typeof GovernanceRetrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/analyze-return'
    | '/assigned'
    | '/audit-log'
    | '/controlled-learning'
    | '/dashboard'
    | '/data-quality'
    | '/fraud-radar'
    | '/model-registry'
    | '/returns'
    | '/review-queue'
    | '/settings'
    | '/case/$caseId'
    | '/governance/retraining'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/analyze-return'
    | '/assigned'
    | '/audit-log'
    | '/controlled-learning'
    | '/dashboard'
    | '/data-quality'
    | '/fraud-radar'
    | '/model-registry'
    | '/returns'
    | '/review-queue'
    | '/settings'
    | '/case/$caseId'
    | '/governance/retraining'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/analyze-return'
    | '/assigned'
    | '/audit-log'
    | '/controlled-learning'
    | '/dashboard'
    | '/data-quality'
    | '/fraud-radar'
    | '/model-registry'
    | '/returns'
    | '/review-queue'
    | '/settings'
    | '/case/$caseId'
    | '/governance/retraining'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnalyzeReturnRoute: typeof AnalyzeReturnRoute
  AssignedRoute: typeof AssignedRoute
  AuditLogRoute: typeof AuditLogRoute
  ControlledLearningRoute: typeof ControlledLearningRoute
  DashboardRoute: typeof DashboardRoute
  DataQualityRoute: typeof DataQualityRoute
  FraudRadarRoute: typeof FraudRadarRoute
  ModelRegistryRoute: typeof ModelRegistryRoute
  ReturnsRoute: typeof ReturnsRoute
  ReviewQueueRoute: typeof ReviewQueueRoute
  SettingsRoute: typeof SettingsRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
  GovernanceRetrainingRoute: typeof GovernanceRetrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze-return': {
      id: '/analyze-return'
      path: '/analyze-return'
      fullPath: '/analyze-return'
      preLoaderRoute: typeof AnalyzeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assigned': {
      id: '/assigned'
      path: '/assigned'
      fullPath: '/assigned'
      preLoaderRoute: typeof AssignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controlled-learning': {
      id: '/controlled-learning'
      path: '/controlled-learning'
      fullPath: '/controlled-learning'
      preLoaderRoute: typeof ControlledLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-radar': {
      id: '/fraud-radar'
      path: '/fraud-radar'
      fullPath: '/fraud-radar'
      preLoaderRoute: typeof FraudRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-registry': {
      id: '/model-registry'
      path: '/model-registry'
      fullPath: '/model-registry'
      preLoaderRoute: typeof ModelRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/retraining': {
      id: '/governance/retraining'
      path: '/governance/retraining'
      fullPath: '/governance/retraining'
      preLoaderRoute: typeof GovernanceRetrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnalyzeReturnRoute: AnalyzeReturnRoute,
  AssignedRoute: AssignedRoute,
  AuditLogRoute: AuditLogRoute,
  ControlledLearningRoute: ControlledLearningRoute,
  DashboardRoute: DashboardRoute,
  DataQualityRoute: DataQualityRoute,
  FraudRadarRoute: FraudRadarRoute,
  ModelRegistryRoute: ModelRegistryRoute,
  ReturnsRoute: ReturnsRoute,
  ReviewQueueRoute: ReviewQueueRoute,
  SettingsRoute: SettingsRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
  GovernanceRetrainingRoute: GovernanceRetrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
